site_name: My MkDocs Website
site_description: A simple MkDocs website
site_author: Your Name
site_url: https://davidmyriel.github.io/mkdocs/

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate 